---
title: "hw-2"
author: "Youngjoo son"
output: html_document
---

```{r}
library(shiny)
library(shinythemes)
library(leaflet)
library(leaflet.extras)
library(rgdal)
```
## Subway Entraces in Newyork

```{r}
# read data
subway <- readOGR("SubwayEntrances.geojson")

# map with markers
leaflet(data = subway) %>%
  addProviderTiles("Esri.WorldTerrain") %>%
  addMarkers()
```

## School Distrct in Newyork

```{r}
# read data
school <- readOGR("SchoolDistricts.geojson")

# polygon map
leaflet(data = school) %>%
  addProviderTiles("Esri.WorldTerrain") %>%
  addPolygons()
```

## Subway Lines in Newyork

```{r}
# read data
subwaylines <- readOGR("SubwayLines.geojson")

# polyline map
leaflet(data = subwaylines) %>%
  addProviderTiles("Esri.WorldTerrain", group = "Esri") %>%
  addProviderTiles("OpenTopoMap", group = "Topo") %>%
  addProviderTiles("Stamen.Watercolor", group = "Watercolor") %>%
  addPolylines() %>%
  # Add layers control
  addLayersControl(
    baseGroups = c("Esri", "Topo", "Watercolor"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

## Projects in Construction in Newyork

```{r}
# read data
cons <- read.csv("Projects_in_Construction.csv")

# Define color factor
palcons <- colorFactor(c("#d73027", "#1a9850"), c("CAP", "CIP"))

leaflet(data = cons) %>%
  addProviderTiles("OpenStreetMap.DE") %>%
  # Add markers
  addCircleMarkers(lng = ~Longitude, lat = ~Latitude, radius = 1.5, color = ~palcons(Project.type), clusterOptions = markerClusterOptions()) %>%
  # Add legend
  addLegend(position = "topright" , pal = palcons, values = cons$Project.type, title = "Project type")
```

